steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - membership-form-backend
      - --source=./components/membership-form-backend
      - --region=northamerica-northeast1
      - --entry-point=main
      - --runtime=nodejs20
      - --trigger-topic=membership-form-backend
      - --timeout=300 # 5 minute timeout
# The following lines should be used only when creating the function
#      - --set-env-vars=ENVIRONMENT=development # should be set appropriately
#      - --service-account=    # should be set appropriately
