steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - membership-form-backend-trigger
      - --source=./components/membership-form-backend-trigger
      - --region=northamerica-northeast1
      - --entry-point=main
      - --runtime=nodejs10
      - --trigger-http
# The following lines should be used only when creating the function
#      - --allow-unauthenticated # requires Security Admin permissions
#      - --service-account=    # should be set appropriately
