steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - expired-members-remover
      - --source=./components/expired-members-remover
      - --region=northamerica-northeast1
      - --entry-point=main
      - --runtime=nodejs20
      - --trigger-topic=expired-members-remover
      - --timeout=300 # 5 minute timeout
# The following lines should be used only when creating the function
#      - --set-env-vars=ENVIRONMENT=development # should be set appropriately
#      - --service-account=    # should be set appropriately
